### ISSUE TITLE
Apply fails to find builds/* dir

### ISSUE THREAD

**Issue by codezninja** [terraform-aws-modules/terraform-aws-lambda#312]
## Description

I'm trying to use Github Actions to run terraform plan & apply as two different jobs. The idea is that the apply job will be dependant on the plan job and download the tfplan after a manually approval. So workflow looks something like this

```yaml
name: Run Terraform Plan & Apply

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_RECREATE_MISSING_LAMBDA_PACKAGE: false
  
jobs:
  terraform-plan:
    runs-on: [self-hosted, Linux]
    steps:
      - name: terraform plan
        uses: MyAction/terraform-plan
        with:
          environment: dev
  terraform-apply:
    needs:
      - terraform-plan
    environment: dev
    runs-on: [self-hosted, Linux]
    steps:
      - name: terraform apply
        uses: MyAction/terraform-apply
        with:
          environment: dev
```

Since the jobs can run on complete different workspaces the workspaces are clean every time. The apply job downloads just the `tfplan` binary from the plan job.

When first running the workflow on a new module the project builds fine. Subsequent runs the `null_resource.archive[0] must be replaced` shows up and I've set both in the module and environment variable the `TF_RECREATE_MISSING_LAMBDA_PACKAGE=false` per the FAQs.

But for some reason the terraform apply fails for the following reason

```bash
module.lambda.null_resource.archive[0]: Destroying... [id=8216471016855497813]
module.lambda.null_resource.archive[0]: Destruction complete after 0s
module.lambda.null_resource.archive[0]: Creating...
module.lambda.null_resource.archive[0]: Provisioning with 'local-exec'...
module.lambda.null_resource.archive[0] (local-exec): Executing: ["python3" ".terraform/modules/lambda/package.py" "build" "--timestamp" "<WARNING: Missing lambda zip artifacts wouldn't be restored>" "builds/c9cf9d0a8a30a2bb379fbbdbc9aea89862cd25f963ee19e36b3ad2619d5b0750.plan.json"]
module.lambda.null_resource.archive[0] (local-exec): Traceback (most recent call last):
module.lambda.null_resource.archive[0] (local-exec):   File ".terraform/modules/lambda/package.py", line 1389, in <module>
module.lambda.null_resource.archive[0] (local-exec):     main()
module.lambda.null_resource.archive[0] (local-exec):   File ".terraform/modules/lambda/package.py", line 1385, in main
module.lambda.null_resource.archive[0] (local-exec):     exit(args.command(args))
module.lambda.null_resource.archive[0] (local-exec):   File ".terraform/modules/lambda/package.py", line 1256, in build_command
module.lambda.null_resource.archive[0] (local-exec):     with open(args.build_plan_file) as f:
module.lambda.null_resource.archive[0] (local-exec): FileNotFoundError: [Errno 2] No such file or directory: 'builds/c9cf9d0a8a30a2bb379fbbdbc9aea89862cd25f963ee19e36b3ad2619d5b0750.plan.json'
```

## Versions

- Module version: 2.36.0
- Terraform version: 1.0.5
- Provider version(s):
```
provider "registry.terraform.io/hashicorp/aws" 
  version     = "3.75.1"
provider "registry.terraform.io/hashicorp/external" 
  version     = "2.2.2"
provider "registry.terraform.io/hashicorp/local" 
  version     = "2.2.2"
provider "registry.terraform.io/hashicorp/null" 
  version     = "3.1.1"
```

Am I misunderstanding the usage of `TF_RECREATE_MISSING_LAMBDA_PACKAGE`. My thoughts currently is that I need to maybe archive the `builds` dir in the plan job and download it before I run the apply job.
