### ISSUE TITLE
Translate Event type API from SAM template.yaml

### ISSUE THREAD

**Issue by SolomonHD** [terraform-aws-modules/terraform-aws-lambda#438]
I'm trying to convert a Lambda Function from a SAM CLI template to Terraform:
```yaml
Resources:
  MessageTransformerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      CodeUri: MessageTransformerFunction
     [...]
      Events:
        MessageTransformer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /transform
            Method: get
```
How would I convert the Events section? I believe it's related to the `aws_lambda_event_source_mapping` resource but I do not see any examples that are similar to my use case.
