### ISSUE TITLE
Allow passing of multiple JSON-Policies 

### ISSUE THREAD

**Issue by Zyntogz** [terraform-aws-modules/terraform-aws-lambda#57]
Hello,

we have a use case where we have the need to pass multiple rendered policy data to the module. However, currently, as far as i can see, only one policy document can be parsed. An implementation of an extension could look like this:

To stay backward-compatible, a new variable/resource is proposed.
```
variables:
  additional_jsons:
    type: list
    default: []
  attach_policies_json:
    type: bool (even list of bools thinkable)
    default: false (or [])
```

implementation example for one boolean value (cant make a pull request as i described in the issue before):

```
resource "aws_iam_policy" "additional_jsons" {
  count = local.create_role && var.attach_policies_json ? length(var.additional_jsons) : 0

  name   = "${var.function_name}-${count.index}"
  policy = var.additional_jsons[count.index]
}

resource "aws_iam_policy_attachment" "additional_jsons" {
  count = local.create_role && var.attach_policy_json ? length(var.additional_jsons) : 0

  name       = "${var.function_name}-${count.index}"
  roles      = [aws_iam_role.lambda[0].name]
  policy_arn = aws_iam_policy.additional_json[count.index].arn
}
```

Are there any things preventing this? In our current situation, because of dependency resolving problems, we cannot use your policy_statements variable (which would be much nicer but it is as it is) and dont want to create X combinations of permission documents for each single permission we want to allow.
